### ISSUE TITLE
Use an up-to-date version of Go

### ISSUE THREAD

**Issue by daenney** [andrewrk/zig-async-demo#2]
These benchmarks were run with Go 1.4. That's a version of Go that's 5 years old. A lot of work has gone into Go in the mean time including having its whole compiler infrastructure ported, SSA being introduced to generate much better code, lots of work on the GC and a bunch more.

Though it might not have been malicious in intent, given this repo is 6 days old running a benchmark with this old a version of Go smells.

It might not make a difference in the results at all, but it would be nice to see the latest version of Go used to run this benchmark, much like the latest version of Zig should be used.

Currently used:
- Go 1.4: December 2014
- Zig 0.5.0: October 2019

Latest:
- Go 1.13: September 2019
- Zig 0.5.0: October 2019

**Comment by andrewrk** [comment]
I'm embarrassed about this mistake. It was a package manager mishap and I didn't do due diligence on double checking the version & date. I've found go 1.13 in the package repo now. I'll redo the numbers with this. Thanks
